[package]
name = "hako"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.2.6", features = ["multipart"] }
deadpool-postgres = "0.9.0"
structopt = "0.3.23"
tokio = { version = "1.12.0", features = ["full"] }
tokio-postgres = "0.7.3"
