[build]
target = "index.html"
release = false
dist = "dist"

# [[proxy]]
# backend = "http://localhost:12321/"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["./pre_build.sh"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "./post_build.sh"]
