name: Cross-compile

on:
  push:
    branches:
      - "main"
      - "actions"
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v2

      # install wasm toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "wasm32-unknown-unknown"

      # install toolchain of current target
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      # rust-cache
      - uses: Swatinem/rust-cache@v1
        with:
          key: "temp-key"

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install tailwindcss
        run: |
          npm install --global tailwindcss
          tailwindcss --help

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Build frontend
        working-directory: ./webapp
        run: |
          rm -rf ./dist
          trunk build --release

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }} --manifest-path server/Cargo.toml

      - uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: hako-${{ github.ref_name }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/hako
